# Generated by Django 6.0.4 on 2026-04-24 01:52

import dfir_pericia.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EvidenceFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_path", models.CharField(max_length=1024, unique=True)),
                ("display_name", models.CharField(max_length=255)),
                (
                    "file_kind",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("html", "HTML"),
                            ("pdf", "PDF"),
                            ("doc", "DOC"),
                            ("docx", "DOCX"),
                            ("image", "Image"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=32,
                    ),
                ),
                ("sha256", models.CharField(blank=True, max_length=64)),
                ("size_bytes", models.BigIntegerField(blank=True, null=True)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dfir_pericia.models.default_dict
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["source_path"],
            },
        ),
        migrations.CreateModel(
            name="PericiaExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                (
                    "scope_snapshot",
                    models.JSONField(
                        blank=True, default=dfir_pericia.models.default_dict
                    ),
                ),
                (
                    "engine_metadata",
                    models.JSONField(
                        blank=True, default=dfir_pericia.models.default_dict
                    ),
                ),
                ("analyzed_files_count", models.PositiveIntegerField(default=0)),
                ("unsupported_files_count", models.PositiveIntegerField(default=0)),
                ("failed_files_count", models.PositiveIntegerField(default=0)),
                ("matched_files_count", models.PositiveIntegerField(default=0)),
                ("findings_count", models.PositiveIntegerField(default=0)),
                (
                    "unsupported_files",
                    models.JSONField(
                        blank=True, default=dfir_pericia.models.default_list
                    ),
                ),
                (
                    "failed_files",
                    models.JSONField(
                        blank=True, default=dfir_pericia.models.default_list
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="PericiaPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                (
                    "point_family",
                    models.CharField(
                        choices=[
                            ("text_email_search", "Text email search"),
                            ("text_keyword_search", "Text keyword search"),
                            (
                                "image_characteristic_detection",
                                "Image characteristic detection",
                            ),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "matching_mode",
                    models.CharField(
                        choices=[
                            ("exact", "Exact"),
                            ("domain", "Domain"),
                            ("regex", "Regex"),
                            ("any", "Any term"),
                            ("all", "All terms"),
                            ("phrase", "Phrase"),
                            ("label", "Label"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(
                        blank=True, default=dfir_pericia.models.default_dict
                    ),
                ),
                (
                    "scope",
                    models.JSONField(
                        blank=True, default=dfir_pericia.models.default_dict
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PericiaFinding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("matched_value", models.TextField()),
                ("context", models.TextField(blank=True)),
                ("confidence", models.FloatField(blank=True, null=True)),
                (
                    "extraction_metadata",
                    models.JSONField(
                        blank=True, default=dfir_pericia.models.default_dict
                    ),
                ),
                (
                    "engine_metadata",
                    models.JSONField(
                        blank=True, default=dfir_pericia.models.default_dict
                    ),
                ),
                (
                    "source_locator",
                    models.JSONField(
                        blank=True, default=dfir_pericia.models.default_dict
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "evidence_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="findings",
                        to="dfir_pericia.evidencefile",
                    ),
                ),
                (
                    "execution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="findings",
                        to="dfir_pericia.periciaexecution",
                    ),
                ),
                (
                    "pericia_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="findings",
                        to="dfir_pericia.periciapoint",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.AddField(
            model_name="periciaexecution",
            name="pericia_point",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="executions",
                to="dfir_pericia.periciapoint",
            ),
        ),
    ]
