# Generated by Django 6.0.4 on 2026-04-28 22:35

import dfir_pericia.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dfir_pericia", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceAnalysisResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("overview", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("analyzed", "Analyzed"),
                            ("partially_analyzed", "Partially analyzed"),
                            ("not_analyzable", "Not analyzable"),
                            ("inaccessible", "Inaccessible"),
                            ("follow_up_required", "Follow-up required"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("technical_reason", models.TextField(blank=True)),
                ("follow_up_recommendation", models.TextField(blank=True)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dfir_pericia.models.default_dict
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["pericia_case", "started_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="PericiaCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("case_reference", models.CharField(max_length=255, unique=True)),
                ("title", models.CharField(blank=True, max_length=255)),
                ("authority_name", models.CharField(blank=True, max_length=255)),
                ("authority_unit", models.CharField(blank=True, max_length=255)),
                ("jurisdiction", models.CharField(blank=True, max_length=255)),
                ("report_date", models.DateField(blank=True, null=True)),
                ("analyst_name", models.CharField(blank=True, max_length=255)),
                ("analyst_badge", models.CharField(blank=True, max_length=128)),
                ("summary", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("intake", "Intake"),
                            ("evidence_registered", "Evidence registered"),
                            ("analysis_in_progress", "Analysis in progress"),
                            ("report_in_progress", "Report in progress"),
                            ("completed", "Completed"),
                            ("blocked", "Blocked"),
                        ],
                        default="intake",
                        max_length=32,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dfir_pericia.models.default_dict
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AnalysisPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=255)),
                ("strategy_notes", models.TextField(blank=True)),
                (
                    "analysis_targets",
                    models.JSONField(
                        blank=True, default=dfir_pericia.models.default_list
                    ),
                ),
                (
                    "scope_snapshot",
                    models.JSONField(
                        blank=True, default=dfir_pericia.models.default_dict
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("skipped", "Skipped"),
                        ],
                        default="planned",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pericia_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="analysis_plans",
                        to="dfir_pericia.periciapoint",
                    ),
                ),
                (
                    "pericia_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis_plans",
                        to="dfir_pericia.periciacase",
                    ),
                ),
            ],
            options={
                "ordering": ["pericia_case", "requested_point__order", "id"],
            },
        ),
        migrations.AddField(
            model_name="periciaexecution",
            name="analysis_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="executions",
                to="dfir_pericia.analysisplan",
            ),
        ),
        migrations.AddField(
            model_name="periciaexecution",
            name="device_analysis_result",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="executions",
                to="dfir_pericia.deviceanalysisresult",
            ),
        ),
        migrations.AddField(
            model_name="periciafinding",
            name="device_analysis_result",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="findings",
                to="dfir_pericia.deviceanalysisresult",
            ),
        ),
        migrations.CreateModel(
            name="EvidenceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("original_device", "Original device"),
                            ("forensic_image", "Forensic image"),
                            ("working_copy", "Working copy"),
                            ("logical_extraction", "Logical extraction"),
                            ("report_output", "Report output"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "acquisition_status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("identified", "Identified"),
                            ("acquired", "Acquired"),
                            ("partial", "Partial"),
                            ("not_acquired", "Not acquired"),
                            ("not_accessible", "Not accessible"),
                        ],
                        default="received",
                        max_length=32,
                    ),
                ),
                ("identifier", models.CharField(blank=True, max_length=255)),
                ("serial_number", models.CharField(blank=True, max_length=255)),
                ("source_path", models.CharField(blank=True, max_length=1024)),
                ("sha256", models.CharField(blank=True, max_length=64)),
                ("size_bytes", models.BigIntegerField(blank=True, null=True)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dfir_pericia.models.default_dict
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "evidence_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="case_evidence_items",
                        to="dfir_pericia.evidencefile",
                    ),
                ),
                (
                    "parent_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="derived_items",
                        to="dfir_pericia.evidenceitem",
                    ),
                ),
                (
                    "pericia_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_items",
                        to="dfir_pericia.periciacase",
                    ),
                ),
            ],
            options={
                "ordering": ["pericia_case", "created_at", "id"],
            },
        ),
        migrations.AddField(
            model_name="deviceanalysisresult",
            name="evidence_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="analysis_results",
                to="dfir_pericia.evidenceitem",
            ),
        ),
        migrations.AddField(
            model_name="deviceanalysisresult",
            name="pericia_case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="device_analysis_results",
                to="dfir_pericia.periciacase",
            ),
        ),
        migrations.CreateModel(
            name="PericiaDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("judicial_request", "Judicial request"),
                            ("technical_report", "Technical report"),
                            ("acta_apertura", "Acta de apertura"),
                            ("annex", "Annex"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                ("file_path", models.CharField(blank=True, max_length=1024)),
                ("extracted_text", models.TextField(blank=True)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dfir_pericia.models.default_dict
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pericia_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="dfir_pericia.periciacase",
                    ),
                ),
            ],
            options={
                "ordering": ["pericia_case", "created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="PreservedArtifact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "artifact_kind",
                    models.CharField(
                        choices=[
                            ("extracted_file", "Extracted file"),
                            ("screenshot", "Screenshot"),
                            ("report_sample", "Report sample"),
                            ("report_attachment", "Report attachment"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                ("display_name", models.CharField(max_length=255)),
                ("storage_path", models.CharField(max_length=1024)),
                ("sha256", models.CharField(blank=True, max_length=64)),
                ("notes", models.TextField(blank=True)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dfir_pericia.models.default_dict
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "evidence_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="preserved_artifacts",
                        to="dfir_pericia.evidenceitem",
                    ),
                ),
                (
                    "pericia_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preserved_artifacts",
                        to="dfir_pericia.periciacase",
                    ),
                ),
                (
                    "source_finding",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="preserved_artifacts",
                        to="dfir_pericia.periciafinding",
                    ),
                ),
            ],
            options={
                "ordering": ["pericia_case", "created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="RequestedPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                ("short_label", models.CharField(blank=True, max_length=255)),
                ("literal_text", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In progress"),
                            ("answered", "Answered"),
                            ("partially_answered", "Partially answered"),
                            ("blocked", "Blocked"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dfir_pericia.models.default_dict
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pericia_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requested_points",
                        to="dfir_pericia.periciacase",
                    ),
                ),
                (
                    "source_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requested_points",
                        to="dfir_pericia.periciadocument",
                    ),
                ),
            ],
            options={
                "ordering": ["pericia_case", "order", "id"],
            },
        ),
        migrations.AddField(
            model_name="analysisplan",
            name="requested_point",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="analysis_plans",
                to="dfir_pericia.requestedpoint",
            ),
        ),
        migrations.CreateModel(
            name="RequestedPointResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In progress"),
                            ("answered", "Answered"),
                            ("partially_answered", "Partially answered"),
                            ("blocked", "Blocked"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("summary", models.TextField(blank=True)),
                ("technical_observations", models.TextField(blank=True)),
                ("rationale", models.TextField(blank=True)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dfir_pericia.models.default_dict
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "device_analysis_results",
                    models.ManyToManyField(
                        blank=True,
                        related_name="requested_point_responses",
                        to="dfir_pericia.deviceanalysisresult",
                    ),
                ),
                (
                    "executions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="requested_point_responses",
                        to="dfir_pericia.periciaexecution",
                    ),
                ),
                (
                    "findings",
                    models.ManyToManyField(
                        blank=True,
                        related_name="requested_point_responses",
                        to="dfir_pericia.periciafinding",
                    ),
                ),
                (
                    "pericia_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requested_point_responses",
                        to="dfir_pericia.periciacase",
                    ),
                ),
                (
                    "preserved_artifacts",
                    models.ManyToManyField(
                        blank=True,
                        related_name="requested_point_responses",
                        to="dfir_pericia.preservedartifact",
                    ),
                ),
                (
                    "requested_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="responses",
                        to="dfir_pericia.requestedpoint",
                    ),
                ),
            ],
            options={
                "ordering": ["pericia_case", "requested_point__order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ReportSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("object", "Object"),
                            ("offered_elements", "Offered elements"),
                            ("tools", "Tools"),
                            ("methodology", "Methodology"),
                            ("obtained_information", "Obtained information"),
                            ("conclusions", "Conclusions"),
                            ("evidence", "Evidence"),
                            ("annex", "Annex"),
                        ],
                        max_length=32,
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField(blank=True)),
                (
                    "structured_data",
                    models.JSONField(
                        blank=True, default=dfir_pericia.models.default_dict
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "device_analysis_results",
                    models.ManyToManyField(
                        blank=True,
                        related_name="report_sections",
                        to="dfir_pericia.deviceanalysisresult",
                    ),
                ),
                (
                    "pericia_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_sections",
                        to="dfir_pericia.periciacase",
                    ),
                ),
                (
                    "preserved_artifacts",
                    models.ManyToManyField(
                        blank=True,
                        related_name="report_sections",
                        to="dfir_pericia.preservedartifact",
                    ),
                ),
                (
                    "responses",
                    models.ManyToManyField(
                        blank=True,
                        related_name="report_sections",
                        to="dfir_pericia.requestedpointresponse",
                    ),
                ),
            ],
            options={
                "ordering": ["pericia_case", "order", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="deviceanalysisresult",
            constraint=models.UniqueConstraint(
                fields=("pericia_case", "evidence_item"),
                name="unique_device_analysis_per_case_evidence",
            ),
        ),
        migrations.AddConstraint(
            model_name="requestedpoint",
            constraint=models.UniqueConstraint(
                fields=("pericia_case", "order"),
                name="unique_requested_point_order_per_case",
            ),
        ),
        migrations.AddConstraint(
            model_name="requestedpointresponse",
            constraint=models.UniqueConstraint(
                fields=("pericia_case", "requested_point"),
                name="unique_response_per_case_requested_point",
            ),
        ),
        migrations.AddConstraint(
            model_name="reportsection",
            constraint=models.UniqueConstraint(
                fields=("pericia_case", "order"),
                name="unique_report_section_order_per_case",
            ),
        ),
    ]
