# Generated by Django 6.0.4 on 2026-04-30 23:45

import dfir_pericia.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dfir_pericia", "0002_deviceanalysisresult_periciacase_analysisplan_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="analysisplan",
            options={
                "ordering": ["pericia_case", "requested_point__order", "id"],
                "verbose_name": "plan de analisis",
                "verbose_name_plural": "planes de analisis",
            },
        ),
        migrations.AlterModelOptions(
            name="deviceanalysisresult",
            options={
                "ordering": ["pericia_case", "started_at", "id"],
                "verbose_name": "resultado de analisis por dispositivo",
                "verbose_name_plural": "resultados de analisis por dispositivo",
            },
        ),
        migrations.AlterModelOptions(
            name="evidencefile",
            options={
                "ordering": ["source_path"],
                "verbose_name": "archivo de evidencia",
                "verbose_name_plural": "archivos de evidencia",
            },
        ),
        migrations.AlterModelOptions(
            name="evidenceitem",
            options={
                "ordering": ["pericia_case", "created_at", "id"],
                "verbose_name": "elemento de evidencia",
                "verbose_name_plural": "elementos de evidencia",
            },
        ),
        migrations.AlterModelOptions(
            name="periciacase",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "caso pericial",
                "verbose_name_plural": "casos periciales",
            },
        ),
        migrations.AlterModelOptions(
            name="periciadocument",
            options={
                "ordering": ["pericia_case", "created_at", "id"],
                "verbose_name": "documento pericial",
                "verbose_name_plural": "documentos periciales",
            },
        ),
        migrations.AlterModelOptions(
            name="periciaexecution",
            options={
                "ordering": ["-started_at"],
                "verbose_name": "ejecucion de pericia",
                "verbose_name_plural": "ejecuciones de pericia",
            },
        ),
        migrations.AlterModelOptions(
            name="periciafinding",
            options={
                "ordering": ["id"],
                "verbose_name": "hallazgo de pericia",
                "verbose_name_plural": "hallazgos de pericia",
            },
        ),
        migrations.AlterModelOptions(
            name="periciapoint",
            options={
                "ordering": ["name"],
                "verbose_name": "punto de pericia",
                "verbose_name_plural": "puntos de pericia",
            },
        ),
        migrations.AlterModelOptions(
            name="preservedartifact",
            options={
                "ordering": ["pericia_case", "created_at", "id"],
                "verbose_name": "artefacto preservado",
                "verbose_name_plural": "artefactos preservados",
            },
        ),
        migrations.AlterModelOptions(
            name="reportsection",
            options={
                "ordering": ["pericia_case", "order", "id"],
                "verbose_name": "seccion del informe",
                "verbose_name_plural": "secciones del informe",
            },
        ),
        migrations.AlterModelOptions(
            name="requestedpoint",
            options={
                "ordering": ["pericia_case", "order", "id"],
                "verbose_name": "punto solicitado",
                "verbose_name_plural": "puntos solicitados",
            },
        ),
        migrations.AlterModelOptions(
            name="requestedpointresponse",
            options={
                "ordering": ["pericia_case", "requested_point__order", "id"],
                "verbose_name": "respuesta a punto solicitado",
                "verbose_name_plural": "respuestas a puntos solicitados",
            },
        ),
        migrations.AlterField(
            model_name="analysisplan",
            name="analysis_targets",
            field=models.JSONField(
                blank=True,
                default=dfir_pericia.models.default_list,
                verbose_name="fuentes a revisar",
            ),
        ),
        migrations.AlterField(
            model_name="analysisplan",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="creado"),
        ),
        migrations.AlterField(
            model_name="analysisplan",
            name="label",
            field=models.CharField(blank=True, max_length=255, verbose_name="etiqueta"),
        ),
        migrations.AlterField(
            model_name="analysisplan",
            name="pericia_case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analysis_plans",
                to="dfir_pericia.periciacase",
                verbose_name="caso pericial",
            ),
        ),
        migrations.AlterField(
            model_name="analysisplan",
            name="pericia_point",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="analysis_plans",
                to="dfir_pericia.periciapoint",
                verbose_name="punto de pericia",
            ),
        ),
        migrations.AlterField(
            model_name="analysisplan",
            name="requested_point",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="analysis_plans",
                to="dfir_pericia.requestedpoint",
                verbose_name="punto solicitado",
            ),
        ),
        migrations.AlterField(
            model_name="analysisplan",
            name="scope_snapshot",
            field=models.JSONField(
                blank=True,
                default=dfir_pericia.models.default_dict,
                verbose_name="snapshot de alcance",
            ),
        ),
        migrations.AlterField(
            model_name="analysisplan",
            name="status",
            field=models.CharField(
                choices=[
                    ("planned", "Planificado"),
                    ("running", "En ejecucion"),
                    ("completed", "Completado"),
                    ("skipped", "Omitido"),
                ],
                default="planned",
                max_length=32,
                verbose_name="estado",
            ),
        ),
        migrations.AlterField(
            model_name="analysisplan",
            name="strategy_notes",
            field=models.TextField(blank=True, verbose_name="notas de estrategia"),
        ),
        migrations.AlterField(
            model_name="analysisplan",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="actualizado"),
        ),
        migrations.AlterField(
            model_name="deviceanalysisresult",
            name="evidence_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="analysis_results",
                to="dfir_pericia.evidenceitem",
                verbose_name="elemento de evidencia",
            ),
        ),
        migrations.AlterField(
            model_name="deviceanalysisresult",
            name="finished_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="fin"),
        ),
        migrations.AlterField(
            model_name="deviceanalysisresult",
            name="follow_up_recommendation",
            field=models.TextField(
                blank=True, verbose_name="recomendacion de seguimiento"
            ),
        ),
        migrations.AlterField(
            model_name="deviceanalysisresult",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dfir_pericia.models.default_dict,
                verbose_name="metadata",
            ),
        ),
        migrations.AlterField(
            model_name="deviceanalysisresult",
            name="overview",
            field=models.TextField(blank=True, verbose_name="resumen tecnico"),
        ),
        migrations.AlterField(
            model_name="deviceanalysisresult",
            name="pericia_case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="device_analysis_results",
                to="dfir_pericia.periciacase",
                verbose_name="caso pericial",
            ),
        ),
        migrations.AlterField(
            model_name="deviceanalysisresult",
            name="started_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="inicio"),
        ),
        migrations.AlterField(
            model_name="deviceanalysisresult",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendiente"),
                    ("analyzed", "Analizado"),
                    ("partially_analyzed", "Analizado parcialmente"),
                    ("not_analyzable", "No analizable"),
                    ("inaccessible", "Inaccesible"),
                    ("follow_up_required", "Requiere seguimiento"),
                ],
                default="pending",
                max_length=32,
                verbose_name="estado",
            ),
        ),
        migrations.AlterField(
            model_name="deviceanalysisresult",
            name="technical_reason",
            field=models.TextField(blank=True, verbose_name="motivo tecnico"),
        ),
        migrations.AlterField(
            model_name="evidencefile",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="creado"),
        ),
        migrations.AlterField(
            model_name="evidencefile",
            name="display_name",
            field=models.CharField(max_length=255, verbose_name="nombre visible"),
        ),
        migrations.AlterField(
            model_name="evidencefile",
            name="file_kind",
            field=models.CharField(
                choices=[
                    ("text", "Texto"),
                    ("html", "HTML"),
                    ("pdf", "PDF"),
                    ("doc", "DOC"),
                    ("docx", "DOCX"),
                    ("image", "Imagen"),
                    ("unknown", "Desconocido"),
                ],
                default="unknown",
                max_length=32,
                verbose_name="tipo de archivo",
            ),
        ),
        migrations.AlterField(
            model_name="evidencefile",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dfir_pericia.models.default_dict,
                verbose_name="metadata",
            ),
        ),
        migrations.AlterField(
            model_name="evidencefile",
            name="sha256",
            field=models.CharField(
                blank=True, max_length=64, verbose_name="hash SHA-256"
            ),
        ),
        migrations.AlterField(
            model_name="evidencefile",
            name="size_bytes",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="tamano en bytes"
            ),
        ),
        migrations.AlterField(
            model_name="evidencefile",
            name="source_path",
            field=models.CharField(
                max_length=1024, unique=True, verbose_name="ruta de origen"
            ),
        ),
        migrations.AlterField(
            model_name="evidencefile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="actualizado"),
        ),
        migrations.AlterField(
            model_name="evidenceitem",
            name="acquisition_status",
            field=models.CharField(
                choices=[
                    ("received", "Recibido"),
                    ("identified", "Identificado"),
                    ("acquired", "Adquirido"),
                    ("partial", "Parcial"),
                    ("not_acquired", "No adquirido"),
                    ("not_accessible", "No accesible"),
                ],
                default="received",
                max_length=32,
                verbose_name="estado de adquisicion",
            ),
        ),
        migrations.AlterField(
            model_name="evidenceitem",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="creado"),
        ),
        migrations.AlterField(
            model_name="evidenceitem",
            name="description",
            field=models.TextField(blank=True, verbose_name="descripcion"),
        ),
        migrations.AlterField(
            model_name="evidenceitem",
            name="evidence_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="case_evidence_items",
                to="dfir_pericia.evidencefile",
                verbose_name="archivo de evidencia",
            ),
        ),
        migrations.AlterField(
            model_name="evidenceitem",
            name="identifier",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="identificador"
            ),
        ),
        migrations.AlterField(
            model_name="evidenceitem",
            name="label",
            field=models.CharField(max_length=255, verbose_name="etiqueta"),
        ),
        migrations.AlterField(
            model_name="evidenceitem",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dfir_pericia.models.default_dict,
                verbose_name="metadata",
            ),
        ),
        migrations.AlterField(
            model_name="evidenceitem",
            name="parent_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="derived_items",
                to="dfir_pericia.evidenceitem",
                verbose_name="elemento padre",
            ),
        ),
        migrations.AlterField(
            model_name="evidenceitem",
            name="pericia_case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evidence_items",
                to="dfir_pericia.periciacase",
                verbose_name="caso pericial",
            ),
        ),
        migrations.AlterField(
            model_name="evidenceitem",
            name="role",
            field=models.CharField(
                choices=[
                    ("original_device", "Dispositivo original"),
                    ("forensic_image", "Imagen forense"),
                    ("working_copy", "Copia de trabajo"),
                    ("logical_extraction", "Extraccion logica"),
                    ("report_output", "Salida de informe"),
                    ("other", "Otro"),
                ],
                max_length=32,
                verbose_name="rol",
            ),
        ),
        migrations.AlterField(
            model_name="evidenceitem",
            name="serial_number",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="numero de serie"
            ),
        ),
        migrations.AlterField(
            model_name="evidenceitem",
            name="sha256",
            field=models.CharField(
                blank=True, max_length=64, verbose_name="hash SHA-256"
            ),
        ),
        migrations.AlterField(
            model_name="evidenceitem",
            name="size_bytes",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="tamano en bytes"
            ),
        ),
        migrations.AlterField(
            model_name="evidenceitem",
            name="source_path",
            field=models.CharField(
                blank=True, max_length=1024, verbose_name="ruta de origen"
            ),
        ),
        migrations.AlterField(
            model_name="evidenceitem",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="actualizado"),
        ),
        migrations.AlterField(
            model_name="periciacase",
            name="analyst_badge",
            field=models.CharField(blank=True, max_length=128, verbose_name="legajo"),
        ),
        migrations.AlterField(
            model_name="periciacase",
            name="analyst_name",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="nombre del perito"
            ),
        ),
        migrations.AlterField(
            model_name="periciacase",
            name="authority_name",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="autoridad"
            ),
        ),
        migrations.AlterField(
            model_name="periciacase",
            name="authority_unit",
            field=models.CharField(blank=True, max_length=255, verbose_name="unidad"),
        ),
        migrations.AlterField(
            model_name="periciacase",
            name="case_reference",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="referencia del caso"
            ),
        ),
        migrations.AlterField(
            model_name="periciacase",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="creado"),
        ),
        migrations.AlterField(
            model_name="periciacase",
            name="jurisdiction",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="jurisdiccion"
            ),
        ),
        migrations.AlterField(
            model_name="periciacase",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dfir_pericia.models.default_dict,
                verbose_name="metadata",
            ),
        ),
        migrations.AlterField(
            model_name="periciacase",
            name="report_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="fecha del informe"
            ),
        ),
        migrations.AlterField(
            model_name="periciacase",
            name="status",
            field=models.CharField(
                choices=[
                    ("intake", "Ingreso"),
                    ("evidence_registered", "Evidencia registrada"),
                    ("analysis_in_progress", "Analisis en curso"),
                    ("report_in_progress", "Informe en curso"),
                    ("completed", "Completado"),
                    ("blocked", "Bloqueado"),
                ],
                default="intake",
                max_length=32,
                verbose_name="estado",
            ),
        ),
        migrations.AlterField(
            model_name="periciacase",
            name="summary",
            field=models.TextField(blank=True, verbose_name="resumen"),
        ),
        migrations.AlterField(
            model_name="periciacase",
            name="title",
            field=models.CharField(blank=True, max_length=255, verbose_name="titulo"),
        ),
        migrations.AlterField(
            model_name="periciacase",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="actualizado"),
        ),
        migrations.AlterField(
            model_name="periciadocument",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="creado"),
        ),
        migrations.AlterField(
            model_name="periciadocument",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("judicial_request", "Requerimiento judicial"),
                    ("technical_report", "Informe tecnico"),
                    ("acta_apertura", "Acta de apertura"),
                    ("annex", "Anexo"),
                    ("other", "Otro"),
                ],
                max_length=32,
                verbose_name="tipo de documento",
            ),
        ),
        migrations.AlterField(
            model_name="periciadocument",
            name="extracted_text",
            field=models.TextField(blank=True, verbose_name="texto extraido"),
        ),
        migrations.AlterField(
            model_name="periciadocument",
            name="file_path",
            field=models.CharField(
                blank=True, max_length=1024, verbose_name="ruta del archivo"
            ),
        ),
        migrations.AlterField(
            model_name="periciadocument",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dfir_pericia.models.default_dict,
                verbose_name="metadata",
            ),
        ),
        migrations.AlterField(
            model_name="periciadocument",
            name="pericia_case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="dfir_pericia.periciacase",
                verbose_name="caso pericial",
            ),
        ),
        migrations.AlterField(
            model_name="periciadocument",
            name="title",
            field=models.CharField(max_length=255, verbose_name="titulo"),
        ),
        migrations.AlterField(
            model_name="periciadocument",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="actualizado"),
        ),
        migrations.AlterField(
            model_name="periciaexecution",
            name="analysis_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="executions",
                to="dfir_pericia.analysisplan",
                verbose_name="plan de analisis",
            ),
        ),
        migrations.AlterField(
            model_name="periciaexecution",
            name="analyzed_files_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="archivos analizados"
            ),
        ),
        migrations.AlterField(
            model_name="periciaexecution",
            name="device_analysis_result",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="executions",
                to="dfir_pericia.deviceanalysisresult",
                verbose_name="resultado por dispositivo",
            ),
        ),
        migrations.AlterField(
            model_name="periciaexecution",
            name="engine_metadata",
            field=models.JSONField(
                blank=True,
                default=dfir_pericia.models.default_dict,
                verbose_name="metadata del motor",
            ),
        ),
        migrations.AlterField(
            model_name="periciaexecution",
            name="failed_files",
            field=models.JSONField(
                blank=True,
                default=dfir_pericia.models.default_list,
                verbose_name="detalle de fallidos",
            ),
        ),
        migrations.AlterField(
            model_name="periciaexecution",
            name="failed_files_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="archivos fallidos"
            ),
        ),
        migrations.AlterField(
            model_name="periciaexecution",
            name="findings_count",
            field=models.PositiveIntegerField(default=0, verbose_name="hallazgos"),
        ),
        migrations.AlterField(
            model_name="periciaexecution",
            name="finished_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="fin"),
        ),
        migrations.AlterField(
            model_name="periciaexecution",
            name="matched_files_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="archivos con coincidencias"
            ),
        ),
        migrations.AlterField(
            model_name="periciaexecution",
            name="pericia_point",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="executions",
                to="dfir_pericia.periciapoint",
                verbose_name="punto de pericia",
            ),
        ),
        migrations.AlterField(
            model_name="periciaexecution",
            name="scope_snapshot",
            field=models.JSONField(
                blank=True,
                default=dfir_pericia.models.default_dict,
                verbose_name="snapshot de alcance",
            ),
        ),
        migrations.AlterField(
            model_name="periciaexecution",
            name="started_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="inicio"),
        ),
        migrations.AlterField(
            model_name="periciaexecution",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendiente"),
                    ("completed", "Completada"),
                    ("failed", "Fallida"),
                ],
                default="pending",
                max_length=32,
                verbose_name="estado",
            ),
        ),
        migrations.AlterField(
            model_name="periciaexecution",
            name="unsupported_files",
            field=models.JSONField(
                blank=True,
                default=dfir_pericia.models.default_list,
                verbose_name="detalle de no soportados",
            ),
        ),
        migrations.AlterField(
            model_name="periciaexecution",
            name="unsupported_files_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="archivos no soportados"
            ),
        ),
        migrations.AlterField(
            model_name="periciafinding",
            name="confidence",
            field=models.FloatField(blank=True, null=True, verbose_name="confianza"),
        ),
        migrations.AlterField(
            model_name="periciafinding",
            name="context",
            field=models.TextField(blank=True, verbose_name="contexto"),
        ),
        migrations.AlterField(
            model_name="periciafinding",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="creado"),
        ),
        migrations.AlterField(
            model_name="periciafinding",
            name="device_analysis_result",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="findings",
                to="dfir_pericia.deviceanalysisresult",
                verbose_name="resultado por dispositivo",
            ),
        ),
        migrations.AlterField(
            model_name="periciafinding",
            name="engine_metadata",
            field=models.JSONField(
                blank=True,
                default=dfir_pericia.models.default_dict,
                verbose_name="metadata del motor",
            ),
        ),
        migrations.AlterField(
            model_name="periciafinding",
            name="evidence_file",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="findings",
                to="dfir_pericia.evidencefile",
                verbose_name="archivo de evidencia",
            ),
        ),
        migrations.AlterField(
            model_name="periciafinding",
            name="execution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="findings",
                to="dfir_pericia.periciaexecution",
                verbose_name="ejecucion",
            ),
        ),
        migrations.AlterField(
            model_name="periciafinding",
            name="extraction_metadata",
            field=models.JSONField(
                blank=True,
                default=dfir_pericia.models.default_dict,
                verbose_name="metadata de extraccion",
            ),
        ),
        migrations.AlterField(
            model_name="periciafinding",
            name="matched_value",
            field=models.TextField(verbose_name="valor encontrado"),
        ),
        migrations.AlterField(
            model_name="periciafinding",
            name="pericia_point",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="findings",
                to="dfir_pericia.periciapoint",
                verbose_name="punto de pericia",
            ),
        ),
        migrations.AlterField(
            model_name="periciafinding",
            name="source_locator",
            field=models.JSONField(
                blank=True,
                default=dfir_pericia.models.default_dict,
                verbose_name="ubicacion de origen",
            ),
        ),
        migrations.AlterField(
            model_name="periciapoint",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="creado"),
        ),
        migrations.AlterField(
            model_name="periciapoint",
            name="enabled",
            field=models.BooleanField(default=True, verbose_name="habilitado"),
        ),
        migrations.AlterField(
            model_name="periciapoint",
            name="matching_mode",
            field=models.CharField(
                choices=[
                    ("exact", "Exacto"),
                    ("domain", "Dominio"),
                    ("regex", "Regex"),
                    ("any", "Cualquier termino"),
                    ("all", "Todos los terminos"),
                    ("phrase", "Frase"),
                    ("label", "Etiqueta"),
                ],
                max_length=32,
                verbose_name="modo de coincidencia",
            ),
        ),
        migrations.AlterField(
            model_name="periciapoint",
            name="name",
            field=models.CharField(max_length=255, verbose_name="nombre"),
        ),
        migrations.AlterField(
            model_name="periciapoint",
            name="parameters",
            field=models.JSONField(
                blank=True,
                default=dfir_pericia.models.default_dict,
                verbose_name="parametros",
            ),
        ),
        migrations.AlterField(
            model_name="periciapoint",
            name="point_family",
            field=models.CharField(
                choices=[
                    ("text_email_search", "Busqueda de correo en texto"),
                    ("text_keyword_search", "Busqueda de palabras en texto"),
                    (
                        "image_characteristic_detection",
                        "Deteccion de caracteristicas en imagen",
                    ),
                ],
                max_length=64,
                verbose_name="familia de punto",
            ),
        ),
        migrations.AlterField(
            model_name="periciapoint",
            name="scope",
            field=models.JSONField(
                blank=True,
                default=dfir_pericia.models.default_dict,
                verbose_name="alcance",
            ),
        ),
        migrations.AlterField(
            model_name="periciapoint",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=255, unique=True, verbose_name="slug"
            ),
        ),
        migrations.AlterField(
            model_name="periciapoint",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="actualizado"),
        ),
        migrations.AlterField(
            model_name="preservedartifact",
            name="artifact_kind",
            field=models.CharField(
                choices=[
                    ("extracted_file", "Archivo extraido"),
                    ("screenshot", "Captura"),
                    ("report_sample", "Muestra para informe"),
                    ("report_attachment", "Adjunto de informe"),
                    ("other", "Otro"),
                ],
                max_length=32,
                verbose_name="tipo de artefacto",
            ),
        ),
        migrations.AlterField(
            model_name="preservedartifact",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="creado"),
        ),
        migrations.AlterField(
            model_name="preservedartifact",
            name="display_name",
            field=models.CharField(max_length=255, verbose_name="nombre visible"),
        ),
        migrations.AlterField(
            model_name="preservedartifact",
            name="evidence_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="preserved_artifacts",
                to="dfir_pericia.evidenceitem",
                verbose_name="elemento de evidencia",
            ),
        ),
        migrations.AlterField(
            model_name="preservedartifact",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dfir_pericia.models.default_dict,
                verbose_name="metadata",
            ),
        ),
        migrations.AlterField(
            model_name="preservedartifact",
            name="notes",
            field=models.TextField(blank=True, verbose_name="notas"),
        ),
        migrations.AlterField(
            model_name="preservedartifact",
            name="pericia_case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="preserved_artifacts",
                to="dfir_pericia.periciacase",
                verbose_name="caso pericial",
            ),
        ),
        migrations.AlterField(
            model_name="preservedartifact",
            name="sha256",
            field=models.CharField(
                blank=True, max_length=64, verbose_name="hash SHA-256"
            ),
        ),
        migrations.AlterField(
            model_name="preservedartifact",
            name="source_finding",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="preserved_artifacts",
                to="dfir_pericia.periciafinding",
                verbose_name="hallazgo de origen",
            ),
        ),
        migrations.AlterField(
            model_name="preservedartifact",
            name="storage_path",
            field=models.CharField(max_length=1024, verbose_name="ruta de resguardo"),
        ),
        migrations.AlterField(
            model_name="preservedartifact",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="actualizado"),
        ),
        migrations.AlterField(
            model_name="reportsection",
            name="content",
            field=models.TextField(blank=True, verbose_name="contenido"),
        ),
        migrations.AlterField(
            model_name="reportsection",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="creado"),
        ),
        migrations.AlterField(
            model_name="reportsection",
            name="device_analysis_results",
            field=models.ManyToManyField(
                blank=True,
                related_name="report_sections",
                to="dfir_pericia.deviceanalysisresult",
                verbose_name="resultados por dispositivo",
            ),
        ),
        migrations.AlterField(
            model_name="reportsection",
            name="order",
            field=models.PositiveIntegerField(verbose_name="orden"),
        ),
        migrations.AlterField(
            model_name="reportsection",
            name="pericia_case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="report_sections",
                to="dfir_pericia.periciacase",
                verbose_name="caso pericial",
            ),
        ),
        migrations.AlterField(
            model_name="reportsection",
            name="preserved_artifacts",
            field=models.ManyToManyField(
                blank=True,
                related_name="report_sections",
                to="dfir_pericia.preservedartifact",
                verbose_name="artefactos preservados",
            ),
        ),
        migrations.AlterField(
            model_name="reportsection",
            name="responses",
            field=models.ManyToManyField(
                blank=True,
                related_name="report_sections",
                to="dfir_pericia.requestedpointresponse",
                verbose_name="respuestas",
            ),
        ),
        migrations.AlterField(
            model_name="reportsection",
            name="section_type",
            field=models.CharField(
                choices=[
                    ("object", "Objeto"),
                    ("offered_elements", "Elementos ofrecidos"),
                    ("tools", "Herramientas"),
                    ("methodology", "Metodologia"),
                    ("obtained_information", "Informacion obtenida"),
                    ("conclusions", "Conclusiones"),
                    ("evidence", "Evidencia"),
                    ("annex", "Anexo"),
                ],
                max_length=32,
                verbose_name="tipo de seccion",
            ),
        ),
        migrations.AlterField(
            model_name="reportsection",
            name="structured_data",
            field=models.JSONField(
                blank=True,
                default=dfir_pericia.models.default_dict,
                verbose_name="datos estructurados",
            ),
        ),
        migrations.AlterField(
            model_name="reportsection",
            name="title",
            field=models.CharField(max_length=255, verbose_name="titulo"),
        ),
        migrations.AlterField(
            model_name="reportsection",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="actualizado"),
        ),
        migrations.AlterField(
            model_name="requestedpoint",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="creado"),
        ),
        migrations.AlterField(
            model_name="requestedpoint",
            name="literal_text",
            field=models.TextField(verbose_name="texto literal"),
        ),
        migrations.AlterField(
            model_name="requestedpoint",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dfir_pericia.models.default_dict,
                verbose_name="metadata",
            ),
        ),
        migrations.AlterField(
            model_name="requestedpoint",
            name="notes",
            field=models.TextField(blank=True, verbose_name="notas"),
        ),
        migrations.AlterField(
            model_name="requestedpoint",
            name="order",
            field=models.PositiveIntegerField(verbose_name="orden"),
        ),
        migrations.AlterField(
            model_name="requestedpoint",
            name="pericia_case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requested_points",
                to="dfir_pericia.periciacase",
                verbose_name="caso pericial",
            ),
        ),
        migrations.AlterField(
            model_name="requestedpoint",
            name="short_label",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="etiqueta corta"
            ),
        ),
        migrations.AlterField(
            model_name="requestedpoint",
            name="source_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="requested_points",
                to="dfir_pericia.periciadocument",
                verbose_name="documento de origen",
            ),
        ),
        migrations.AlterField(
            model_name="requestedpoint",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendiente"),
                    ("in_progress", "En curso"),
                    ("answered", "Respondido"),
                    ("partially_answered", "Respondido parcialmente"),
                    ("blocked", "Bloqueado"),
                ],
                default="pending",
                max_length=32,
                verbose_name="estado",
            ),
        ),
        migrations.AlterField(
            model_name="requestedpoint",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="actualizado"),
        ),
        migrations.AlterField(
            model_name="requestedpointresponse",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="creado"),
        ),
        migrations.AlterField(
            model_name="requestedpointresponse",
            name="device_analysis_results",
            field=models.ManyToManyField(
                blank=True,
                related_name="requested_point_responses",
                to="dfir_pericia.deviceanalysisresult",
                verbose_name="resultados por dispositivo",
            ),
        ),
        migrations.AlterField(
            model_name="requestedpointresponse",
            name="executions",
            field=models.ManyToManyField(
                blank=True,
                related_name="requested_point_responses",
                to="dfir_pericia.periciaexecution",
                verbose_name="ejecuciones",
            ),
        ),
        migrations.AlterField(
            model_name="requestedpointresponse",
            name="findings",
            field=models.ManyToManyField(
                blank=True,
                related_name="requested_point_responses",
                to="dfir_pericia.periciafinding",
                verbose_name="hallazgos",
            ),
        ),
        migrations.AlterField(
            model_name="requestedpointresponse",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dfir_pericia.models.default_dict,
                verbose_name="metadata",
            ),
        ),
        migrations.AlterField(
            model_name="requestedpointresponse",
            name="pericia_case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requested_point_responses",
                to="dfir_pericia.periciacase",
                verbose_name="caso pericial",
            ),
        ),
        migrations.AlterField(
            model_name="requestedpointresponse",
            name="preserved_artifacts",
            field=models.ManyToManyField(
                blank=True,
                related_name="requested_point_responses",
                to="dfir_pericia.preservedartifact",
                verbose_name="artefactos preservados",
            ),
        ),
        migrations.AlterField(
            model_name="requestedpointresponse",
            name="rationale",
            field=models.TextField(blank=True, verbose_name="fundamento"),
        ),
        migrations.AlterField(
            model_name="requestedpointresponse",
            name="requested_point",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="responses",
                to="dfir_pericia.requestedpoint",
                verbose_name="punto solicitado",
            ),
        ),
        migrations.AlterField(
            model_name="requestedpointresponse",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendiente"),
                    ("in_progress", "En curso"),
                    ("answered", "Respondida"),
                    ("partially_answered", "Respondida parcialmente"),
                    ("blocked", "Bloqueada"),
                ],
                default="pending",
                max_length=32,
                verbose_name="estado",
            ),
        ),
        migrations.AlterField(
            model_name="requestedpointresponse",
            name="summary",
            field=models.TextField(blank=True, verbose_name="resumen"),
        ),
        migrations.AlterField(
            model_name="requestedpointresponse",
            name="technical_observations",
            field=models.TextField(blank=True, verbose_name="observaciones tecnicas"),
        ),
        migrations.AlterField(
            model_name="requestedpointresponse",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="actualizado"),
        ),
    ]
