# Generated by Django 6.0.4 on 2026-05-01 00:02

from django.db import migrations, models


def backfill_evidence_files(apps, schema_editor):
    EvidenceItem = apps.get_model("dfir_pericia", "EvidenceItem")
    through = EvidenceItem.evidence_files.through
    through_objects = []

    for item in EvidenceItem.objects.exclude(evidence_file_id__isnull=True).only(
        "id", "evidence_file_id"
    ):
        through_objects.append(
            through(
                evidenceitem_id=item.id,
                evidencefile_id=item.evidence_file_id,
            )
        )

    if through_objects:
        through.objects.bulk_create(through_objects, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ("dfir_pericia", "0003_alter_analysisplan_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evidenceitem",
            name="evidence_files",
            field=models.ManyToManyField(
                blank=True,
                related_name="linked_evidence_items",
                to="dfir_pericia.evidencefile",
                verbose_name="archivos de evidencia",
            ),
        ),
        migrations.RunPython(backfill_evidence_files, migrations.RunPython.noop),
    ]
