# Generated by Django 6.0.4 on 2026-05-01 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dfir_pericia", "0004_evidenceitem_evidence_files"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="requestedpoint",
            name="source_document",
        ),
    ]
