# Generated by Codex on 2026-05-03

from django.db import migrations, models
import django.db.models.deletion
from django.db.models import Q


def _infer_source_kind(item):
    evidence_file = getattr(item, "evidence_file", None)
    if evidence_file is not None:
        metadata = evidence_file.metadata if isinstance(evidence_file.metadata, dict) else {}
        if metadata.get("is_directory") is True:
            return "directory"
        if evidence_file.source_path:
            return "file"

    source_path = str(getattr(item, "source_path", "") or "").strip()
    basename = source_path.rsplit("/", 1)[-1]
    if "." in basename:
        return "file"
    return "directory"


def backfill_evidence_item_sources(apps, schema_editor):
    EvidenceItem = apps.get_model("dfir_pericia", "EvidenceItem")
    EvidenceItemSource = apps.get_model("dfir_pericia", "EvidenceItemSource")

    for item in EvidenceItem.objects.exclude(source_path="").iterator():
        source_path = str(item.source_path or "").strip()
        if not source_path:
            continue
        EvidenceItemSource.objects.get_or_create(
            evidence_item_id=item.pk,
            source_path=source_path,
            defaults={
                "role": "primary",
                "source_kind": _infer_source_kind(item),
                "position": 0,
                "metadata": {},
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("dfir_pericia", "0005_remove_requestedpoint_source_document"),
    ]

    operations = [
        migrations.CreateModel(
            name="EvidenceItemSource",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("role", models.CharField(choices=[("primary", "Fuente principal"), ("supporting", "Fuente asociada")], max_length=16)),
                ("source_kind", models.CharField(choices=[("file", "Archivo"), ("directory", "Carpeta")], max_length=16)),
                ("source_path", models.CharField(max_length=1024)),
                ("position", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("evidence_item", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="sources", to="dfir_pericia.evidenceitem")),
            ],
            options={
                "verbose_name": "fuente de evidencia del dispositivo",
                "verbose_name_plural": "fuentes de evidencia del dispositivo",
                "ordering": ["evidence_item", "position", "created_at", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="evidenceitemsource",
            constraint=models.UniqueConstraint(fields=("evidence_item", "source_path"), name="unique_evidence_item_source_path"),
        ),
        migrations.AddConstraint(
            model_name="evidenceitemsource",
            constraint=models.UniqueConstraint(condition=Q(role="primary"), fields=("evidence_item",), name="unique_primary_source_per_evidence_item"),
        ),
        migrations.RunPython(backfill_evidence_item_sources, migrations.RunPython.noop),
    ]
