# Generated by Django 6.0.4 on 2026-04-30 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dfir_evidence", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="preservedartifactproxy",
            options={
                "verbose_name": "artefacto preservado",
                "verbose_name_plural": "artefactos preservados",
            },
        ),
    ]
